apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: digisos-alerts
  namespace: teamdigisos
  labels:
    namespace: teamdigisos
spec:
  groups:
    - name: digisos-dev-gcp-alerts
      rules:
        - alert: soknad-api-ingen-soknader
          expr: |-
            (
              sum(increase(start_soknad_counter_total[10m])) == 0
              and
              (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 21)
            )
          annotations:
            consequence: Får ingen søknader fra brukere siste 10 minutter.
          labels:
            severity: danger
            namespace: teamdigisos
        - alert: soknad-api-ingen-soknader_sendt
          expr: |-
            (
                sum(increase(sendt_soknad_digisosapi_counter_total[10m])) == 0
                and
                (day_of_week() >= 1 and day_of_week() <= 5 and hour() >= 8 and hour() < 21)
              )
          annotations:
            consequence: Får ingen søknader fra brukere siste 10 minutter.
          labels:
            severity: danger
            namespace: teamdigisos

        - alert: soknad-api-gamle-soknader-status-sendt
          expr: sum(antall_gamle_soknader_status_sendt) > 0
          for: 3h
          annotations:
            summary: Det finnes søknader med status sendt som er eldre en x antall dager.
            consequence: Søknaden(e) er enda ikke motatt av Fagsystem
          labels:
            severity: danger
            namespace: teamdigisos