apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: digisos-alerts
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  groups:
    - name: digisos-dev-gcp-alerts
      rules:
        - alert: digisos-app-nede
          expr: kube_deployment_status_replicas_available{deployment=~"sosialhjelp-soknad-api-dev|sosialhjelp-soknad-dev|sosialhjelp-innsyn-api-dev|sosialhjelp-innsyn-dev"} == 0
          for: 2m
          annotations:
            consequence: Applikasjon er utilgjengelig
            action: "Se `kubectl describe pod {{ $labels.pod }}` for events, og `kubectl logs {{ $labels.pod }}` for logger"
            summary: "{{ $labels.deployment }} er nede i dev-gcp"
          labels:
            namespace: teamdigisos
            severity: danger
        - alert: digisos-app-kontinuerlig-restart
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sosialhjelp-soknad-api-dev|sosialhjelp-soknad-dev|sosialhjelp-innsyn-api-dev|sosialhjelp-innsyn-dev"}[30m])) by (container) > 2
          for: 5m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
            summary: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
          labels:
            namespace: teamdigisos
            severity: danger
        - alert: høy feilrate i logger
          expr: (100 * sum by (app, namespace) (rate(log_messages_errors{app=~"sosialhjelp-soknad-api-dev|sosialhjelp-soknad-dev|sosialhjelp-innsyn-api-dev|sosialhjelp-innsyn-dev", level="Error"}[10m]))) > 10
          for: 3m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Sjekk loggene til app {{ $labels.app }} for å se hvorfor det er så mye feil"
            summary: "Høy feilrate i logger på app {{ $labels.app }}"
            labels:
              namespace: teamdigisos
