apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: digisos-alerts
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  groups:
    - name: digisos-soknad-api-alerts
      rules:
        - alert: soknad-api-ingen-soknader
          expr: |-
            (
              sum(increase(start_soknad_counter_total[5m]))=0
              and
              (hour() >= 8 and hour() < 21)
            )
          annotations:
            consequence: Får ingen søknader fra brukere siste 5 minutter.
          labels:
            severity: danger
            team: teamdigisos