apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: digisos-alerts
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  groups:
    - name: digisos-soknad-api-alerts
      rules:
        - alert: soknad-api-low-creation-rate
          expr: |-
            (
              sum(increase(http_server_requests_seconds_count{status="200", app="sosialhjelp-soknad-api", uri="/soknader/opprettSoknad"}[5m])) < 1
              and
              (hour() >= 9 and hour() < 21)
            ) or (
              sum(increase(http_server_requests_seconds_count{status="200", app="sosialhjelp-soknad-api", uri="/soknader/opprettSoknad"}[30m])) < 1
            )
          annotations:
            consequence: Brukere kan være forhindret fra å opprette søknader
          labels:
            severity: danger
            team: teamdigisos

        - alert: soknad-api-low-submission-rate
          expr: |-
            (
              sum(increase(http_server_requests_seconds_count{status="200", app="sosialhjelp-soknad-api", uri="/soknader/{behandlingsId}/actions/send"}[5m])) < 1
              and
              (hour() >= 9 and hour() < 21)
            ) or (
              sum(increase(http_server_requests_seconds_count{status="200", app="sosialhjelp-soknad-api", uri="/soknader/{behandlingsId}/actions/send"}[30m])) < 1
            )
          annotations:
            consequence: Brukere kan være forhindret fra å sende søknader
          labels:
            severity: danger
            team: teamdigisos

        - alert: soknad-api-response-time-high
          expr: |-
            sum(rate(http_client_requests_seconds_sum{app="sosialhjelp-soknad-api"}[5m])) /
            sum(rate(http_client_requests_seconds_count{app="sosialhjelp-soknad-api"}[5m]))
          annotations:
            consequence: Brukere kan oppleve treg respons
          labels:
            severity: warning
            team: teamdigisos

    - name: digisos-innsyn-api-alerts
      rules:
        - alert: innsyn-api-low-ettersendelse-rate
          expr: |-
            sum(increase(http_server_requests_seconds_count{app="sosialhjelp-innsyn-api", namespace="teamdigisos", status=~"200|202|204|302", method="POST", uri="/api/v1/innsyn/{fiksDigisosId}/vedlegg"}[30m])) < 1
          annotations:
            consequence: Brukere kan være forhindret fra å ettersende vedlegg
          labels:
            severity: danger
            team: teamdigisos

        - alert: innsyn-api-response-time-high
          expr: |-
            sum(rate(http_client_requests_seconds_sum{app="sosialhjelp-innsyn-api"}[5m])) /
            sum(rate(http_client_requests_seconds_count{app="sosialhjelp-innsyn-api"}[5m]))
          annotations:
            consequence: Brukere kan oppleve treg respons
          labels:
            severity: warning
            team: teamdigisos

    - name: digisos-prod-gcp-alerts
      rules:
        - alert: digisos-app-nede
          expr: kube_deployment_status_replicas_available{app=~"sosialhjelp-avtaler-api|sosialhjelp-avtaler|sosialhjelp-soknad-api|sosialhjelp-innsyn|sosialhjelp-innsyn-api"} == 0
          for: 2m
          annotations:
            consequence: Applikasjon er utilgjengelig
            action: "Se `kubectl describe pod {{ $labels.pod }}` for events, og `kubectl logs {{ $labels.pod }}` for logger"
            summary: "{{ $labels.deployment }} er nede i prod-gcp"
          labels:
            namespace: teamdigisos
            severity: danger
        - alert: digisos-app-kontinuerlig-restart
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sosialhjelp-avtaler-api|sosialhjelp-avtaler|sosialhjelp-soknad-api|sosialhjelp-innsyn|sosialhjelp-innsyn-api"}[30m])) by (container) > 2
          for: 5m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
            summary: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
          labels:
            namespace: teamdigisos
            severity: danger
        - alert: høy feilrate i logger
          expr: (600 * sum by (app, namespace) (rate(log_messages_errors{app=~"sosialhjelp-avtaler-api|sosialhjelp-avtaler|sosialhjelp-soknad|sosialhjelp-soknad-api|sosialhjelp-innsyn|sosialhjelp-innsyn-api",level="Error"}[10m]))) > 10
          for: 3m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Sjekk loggene til app {{ $labels.app }} for å se hvorfor det er så mye feil"
            summary: "Høy feilrate i {{ $labels.app }}"
          labels:
            namespace: teamdigisos
        - alert: feil i selftest
          expr: selftests_aggregate_result_status{namespace="teamdigisos"} == 1
          for: 1m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Sjekk {{ $labels.app }} i prod-gcp sin selftest for å se hva som er galt"
            description: "Feil i selftest - {{ $labels.app }} i prod-gcp"
          labels:
            namespace: teamdigisos
