apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: digisos-alerts
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  groups:
    - name: digisos-prod-fss-alerts
      rules:
        - alert: digisos-app-nede
          expr: kube_deployment_status_replicas_available{app=~"sosialhjelp-modia-api|sosialhjelp-modia|sosialhjelp-soknad-api|sosialhjelp-innsyn-api"} == 0
          for: 2m
          annotations:
            consequence: Applikasjon er utilgjengelig
            action: "Se `kubectl describe pod {{ $labels.pod }}` for events, og `kubectl logs {{ $labels.pod }}` for logger"
            summary: "{{ $labels.deployment }} er nede i prod-fss"
          labels:
            namespace: teamdigisos
            severity: danger
        - alert: digisos-app-kontinuerlig-restart
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sosialhjelp-modia-api|sosialhjelp-modia|sosialhjelp-soknad-api|sosialhjelp-innsyn-api"}[30m])) by (container) > 2
          for: 5m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
            summary: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
          labels:
            namespace: teamdigisos
            severity: danger
        - alert: høy feilrate i logger
          expr: (600 * sum by (app, namespace) (rate(log_messages_errors{app=~"sosialhjelp-modia-api|sosialhjelp-soknad-api|sosialhjelp-innsyn-api",level="Error"}[10m]))) > 10
          for: 3m
          annotations:
            consequence: Applikasjon kan være ustabil
            action: "Sjekk loggene til app {{ $labels.app }} for å se hvorfor det er så mye feil"
            summary: "Høy feilrate i {{ $labels.app }}"
          labels:
            namespace: teamdigisos
        - alert: feil i selftest
          expr: selftests_aggregate_result_status{namespace="teamdigisos"} == 1
          for: 1m
          annotations:
            action: "Sjekk {{ $labels.app }} i prod-fss sin selftest for å se hva som er galt"
            summary: "Feil i selftest - {{ $labels.app }} i prod-fss"
          labels:
            namespace: teamdigisos
        - alert: drastisk nedgang i requests til soknad-api
          expr: |
            1 / sum(predict_linear(
                http_server_requests_seconds_count{
                  app="sosialhjelp-soknad-api",
                  uri=~"/soknader.*"
                }[10m], 1800))
              / sum(avg_over_time(
                http_server_requests_seconds_count{
                  app="sosialhjelp-soknad-api"
                  uri=~"/soknader.*"
                }[30m] offset 60m))
            > 60.0
          for: 1m
          annotations:
              summary: "API-kall mot soknad-api synker svært raskt"
              action: "Sjekk om sosialhjelp-soknad og/eller login-service er i drift"
              consequence: "Det kan være problemer med sosialhjelp-soknad frontend, sjekk https://nav.no/sosialhjelp/soknad"
              message: |
                Forespørsler mot soknad-api synker svært raskt.
                Dette varselet sammenligner forventet trafikk fra trenden for de siste 10 minutter med faktisk trafikk for en time siden.
                Varselet utløses hvis den forutsagte trafikken er mindre enn 1/60 av gjennomsnittet for tidsrommet mellom 30 til 60 min siden.
          labels:
            namespace: teamdigisos