name: Deploy alerts
on:
  push:
    branches:
      - 'master'

jobs:
  deploy-dev-sbs:
    name: Deploy to dev-sbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: dev-alerts.yml

  deploy-prod-sbs:
    name: Deploy to prod-sbs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: prod-alerts.yml
